// frontend/src/services/CodeGenerator.js

/**
 * CodeGenerator.js
 * ----------------
 * Converts an App Blueprint into real frontend code.
 * Output format: React + Next.js (stable, deterministic)
 *
 * This generator produces:
 *  - pages/
 *  - components/
 *  - layout
 *  - navigation
 *
 * The output is a fully runnable Next.js app structure.
 */

export function generateFrontendCode(blueprint) {
    return {
        "package.json": generatePackageJson(blueprint),
        "next.config.js": generateNextConfig(),
        "pages/_app.js": generateAppWrapper(),
        ...generatePages(blueprint),
        ...generateComponents(blueprint)
    };
}

/**
 * Generate package.json
 */
function generatePackageJson(blueprint) {
    return JSON.stringify(
        {
            name: slugify(blueprint.name),
            version: "1.0.0",
            private: true,
            scripts: {
                dev: "next dev",
                build: "next build",
                start: "next start"
            },
            dependencies: {
                react: "18.x",
                "react-dom": "18.x",
                next: "14.x"
            }
        },
        null,
        2
    );
}

/**
 * Generate next.config.js
 */
function generateNextConfig() {
    return `
/**
 * Auto-generated by Blue Lotus
 */
module.exports = {
    reactStrictMode: true
};
`;
}

/**
 * Generate _app.js wrapper
 */
function generateAppWrapper() {
    return `
import "../styles.css";

export default function App({ Component, pageProps }) {
    return <Component {...pageProps} />;
}
`;
}

/**
 * Generate pages from blueprint.pages
 */
function generatePages(blueprint) {
    const output = {};

    blueprint.pages.forEach((page) => {
        const route = page.route === "/" ? "index" : page.route.slice(1);

        output[\`pages/\${route}.js\`] = `
/**
 * Auto-generated page: ${page.name}
 */
import React from "react";
import { Page } from "../components/Page";

export default function ${toComponentName(page.name)}() {
    return <Page blocks={${JSON.stringify(page.content, null, 2)}} />;
}
`;
    });

    return output;
}

/**
 * Generate shared components
 */
function generateComponents(blueprint) {
    return {
        "components/Page.js": `
/**
 * Auto-generated Page component
 */
import React from "react";

export function Page({ blocks }) {
    return (
        <div style={styles.page}>
            {blocks.map((block) => (
                <div key={block.id} style={styles.block}>
                    {block.value}
                </div>
            ))}
        </div>
    );
}

const styles = {
    page: {
        padding: "40px",
        fontFamily: "sans-serif",
        color: "#222"
    },
    block: {
        marginBottom: "20px",
        fontSize: "18px",
        lineHeight: "1.6"
    }
};
`
    };
}

/**
 * Helpers
 */
function slugify(str) {
    return str
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "");
}

function toComponentName(str) {
    return str
        .replace(/[^a-zA-Z0-9]/g, " ")
        .split(" ")
        .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
        .join("");
}
