import React, { useState, useRef, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import Logo from '../components/Logo';
import { Button } from '../components/ui/button';
import { ScrollArea } from '../components/ui/scroll-area';
import { Textarea } from '../components/ui/textarea';
import {
  Send,
  ArrowLeft,
  Sparkles,
  Smartphone,
  Monitor,
  Tablet,
  Loader2,
  Check,
  Circle,
  Bot,
  User,
  Rocket,
  RefreshCw,
  Eye,
  PanelLeftClose,
  PanelLeft,
  Zap,
  MoreHorizontal,
  Layout,
  Database,
  GitBranch,
  ChevronRight,
  ChevronDown,
  Home,
  BarChart3,
  Settings,
  Bell,
  Plus,
  Lightbulb,
  Globe,
  FileText,
  Users,
  ShoppingCart,
  MessageSquare,
} from 'lucide-react';

// Mock generated project structure - would be generated by AI
const generateMockStructure = (type) => ({
  screens: [
    { id: 's1', name: 'Home', icon: Home },
    { id: 's2', name: 'Dashboard', icon: BarChart3 },
    { id: 's3', name: 'Profile', icon: User },
    { id: 's4', name: 'Settings', icon: Settings },
  ],
  pages: type === 'website' || type === 'both' ? [
    { id: 'p1', name: 'Landing', icon: Globe },
    { id: 'p2', name: 'About', icon: FileText },
    { id: 'p3', name: 'Pricing', icon: ShoppingCart },
    { id: 'p4', name: 'Contact', icon: MessageSquare },
  ] : [],
  dataModels: [
    { id: 'd1', name: 'Users', fields: ['id', 'name', 'email', 'avatar'] },
    { id: 'd2', name: 'Posts', fields: ['id', 'title', 'content', 'author', 'createdAt'] },
  ],
  flows: [
    { id: 'f1', name: 'User Sign Up', steps: ['Collect info', 'Validate', 'Create account', 'Send welcome'] },
    { id: 'f2', name: 'Create Post', steps: ['Enter content', 'Add media', 'Publish'] },
  ],
});

const suggestedPrompts = [
  'Add a new screen for user onboarding',
  'Create a data model for products',
  'Add a checkout flow',
  'Change the color scheme to dark mode',
  'Add a notification center',
  'Create a settings page with profile editing',
];

const Builder = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  const [project, setProject] = useState(null);
  const [structure, setStructure] = useState(null);
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationSteps, setGenerationSteps] = useState([]);
  const [currentStep, setCurrentStep] = useState(-1);
  const [showSidebar, setShowSidebar] = useState(true);
  const [deviceView, setDeviceView] = useState('desktop');
  const [selectedScreen, setSelectedScreen] = useState(null);
  const [environment, setEnvironment] = useState('draft');
  const [expandedSections, setExpandedSections] = useState(['screens', 'pages', 'data', 'flows']);

  useEffect(() => {
    // Load project from localStorage
    const storedProject = localStorage.getItem(`project_${id}`);
    if (storedProject) {
      const proj = JSON.parse(storedProject);
      setProject(proj);
      setStructure(generateMockStructure(proj.type));
      
      // Initial AI message based on project
      setMessages([{
        id: '1',
        role: 'assistant',
        content: `I've generated your ${proj.type === 'app' ? 'app' : proj.type === 'website' ? 'website' : 'app and website'} based on your description:\n\n"${proj.description}"\n\n**What I created:**\n• ${proj.type !== 'website' ? '4 screens (Home, Dashboard, Profile, Settings)' : ''}\n${proj.type !== 'app' ? '• 4 pages (Landing, About, Pricing, Contact)' : ''}\n• 2 data models (Users, Posts)\n• 2 flows (User Sign Up, Create Post)\n\nYou can refine anything by describing what you want to change. Try commands like:\n• "Add a new screen for..."\n• "Change the style to..."\n• "Add a data model for..."`,
        timestamp: new Date(),
      }]);
    } else {
      setProject({ id, name: 'My Project', type: 'app', description: '' });
      setStructure(generateMockStructure('app'));
      setMessages([{
        id: '1',
        role: 'assistant',
        content: "Welcome to Blue Lotus! I'm your AI builder. Describe what you want to create or modify, and I'll generate it for you.\n\nNo coding required - just tell me what you need in plain language.",
        timestamp: new Date(),
      }]);
    }
  }, [id]);

  useEffect(() => {
    if (structure?.screens?.length > 0 && !selectedScreen) {
      setSelectedScreen(structure.screens[0]);
    }
  }, [structure, selectedScreen]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const simulateAIGeneration = async (userInput) => {
    const steps = [
      { text: 'Understanding your request...', duration: 600 },
      { text: 'Planning changes...', duration: 800 },
      { text: 'Generating structures...', duration: 1000 },
      { text: 'Updating preview...', duration: 600 },
    ];

    setGenerationSteps(steps.map(s => s.text));
    setCurrentStep(0);

    for (let i = 0; i < steps.length; i++) {
      setCurrentStep(i);
      await new Promise(resolve => setTimeout(resolve, steps[i].duration));
    }

    // Generate contextual response
    const lowercaseInput = userInput.toLowerCase();
    let response = '';

    if (lowercaseInput.includes('screen') || lowercaseInput.includes('page')) {
      response = `Done! I've added a new screen based on your request.\n\n**Changes made:**\n• Created new screen layout\n• Added navigation link\n• Set up data bindings\n\nThe preview has been updated. What else would you like to modify?`;
    } else if (lowercaseInput.includes('style') || lowercaseInput.includes('color') || lowercaseInput.includes('theme')) {
      response = `Done! I've updated the visual style.\n\n**Changes made:**\n• Updated color palette\n• Adjusted typography\n• Applied consistent styling across all screens\n\nThe preview reflects the new design. Let me know if you'd like any adjustments.`;
    } else if (lowercaseInput.includes('data') || lowercaseInput.includes('model')) {
      response = `Done! I've created a new data model.\n\n**Changes made:**\n• Created data structure with appropriate fields\n• Set up relationships\n• Added validation rules\n\nThe model is now available in your project. Would you like to connect it to a screen?`;
    } else if (lowercaseInput.includes('flow') || lowercaseInput.includes('action')) {
      response = `Done! I've set up the new flow.\n\n**Changes made:**\n• Created flow steps\n• Connected to relevant screens\n• Added logic handlers\n\nThe flow is active. Want to add any conditions or additional steps?`;
    } else {
      response = `Done! I've processed your request: "${userInput}"\n\n**Changes made:**\n• Updated the project structure\n• Refreshed the preview\n\nWhat else would you like to create or modify?`;
    }

    return response;
  };

  const handleSendMessage = async () => {
    if (!inputValue.trim() || isGenerating) return;

    const userMessage = {
      id: Date.now().toString(),
      role: 'user',
      content: inputValue,
      timestamp: new Date(),
    };

    setMessages(prev => [...prev, userMessage]);
    const userInput = inputValue;
    setInputValue('');
    setIsGenerating(true);

    try {
      const response = await simulateAIGeneration(userInput);

      const aiMessage = {
        id: (Date.now() + 1).toString(),
        role: 'assistant',
        content: response,
        timestamp: new Date(),
      };

      setMessages(prev => [...prev, aiMessage]);
    } finally {
      setIsGenerating(false);
      setGenerationSteps([]);
      setCurrentStep(-1);
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const handleSuggestionClick = (suggestion) => {
    setInputValue(suggestion);
    inputRef.current?.focus();
  };

  const toggleSection = (section) => {
    setExpandedSections(prev =>
      prev.includes(section) ? prev.filter(s => s !== section) : [...prev, section]
    );
  };

  const formatTime = (date) => {
    return new Date(date).toLocaleTimeString('en-US', {
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
    });
  };

  const envColors = {
    draft: 'bg-gray-500',
    staging: 'bg-yellow-500',
    live: 'bg-green-500',
  };

  if (!project || !structure) {
    return (
      <div className="h-screen bg-gray-950 flex items-center justify-center">
        <Loader2 className="w-8 h-8 text-blue-500 animate-spin" />
      </div>
    );
  }

  return (
    <div className="h-screen bg-gray-950 flex flex-col overflow-hidden">
      {/* Top Bar */}
      <header className="h-14 border-b border-gray-800 bg-gray-900/80 backdrop-blur-sm flex items-center justify-between px-4 flex-shrink-0">
        <div className="flex items-center gap-4">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => navigate('/dashboard')}
            className="text-gray-400 hover:text-white hover:bg-gray-800"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Dashboard
          </Button>
          <div className="h-5 w-px bg-gray-800" />
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
            <span className="text-white font-medium">{project.name}</span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* Environment Selector */}
          <div className="flex items-center bg-gray-800 rounded-lg p-1">
            {['draft', 'staging', 'live'].map((env) => (
              <button
                key={env}
                onClick={() => setEnvironment(env)}
                className={`px-3 py-1.5 text-xs font-medium rounded-md transition-all flex items-center gap-1.5 ${
                  environment === env
                    ? 'bg-gray-700 text-white'
                    : 'text-gray-400 hover:text-white'
                }`}
              >
                <span className={`w-1.5 h-1.5 rounded-full ${envColors[env]}`} />
                {env.charAt(0).toUpperCase() + env.slice(1)}
              </button>
            ))}
          </div>

          <div className="h-5 w-px bg-gray-800" />

          <Button
            variant="ghost"
            size="sm"
            className="text-gray-400 hover:text-white hover:bg-gray-800"
          >
            <RefreshCw className="w-4 h-4 mr-2" />
            Regenerate
          </Button>

          <Button size="sm" className="bg-blue-600 hover:bg-blue-700 text-white">
            <Rocket className="w-4 h-4 mr-2" />
            Publish
          </Button>
        </div>
      </header>

      {/* Main Content */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left Panel - AI Chat (Emergent Style) */}
        <div
          className={`${
            showSidebar ? 'w-[420px]' : 'w-0'
          } border-r border-gray-800 flex flex-col transition-all duration-300 overflow-hidden bg-gray-900/30`}
        >
          {/* Chat Header */}
          <div className="p-4 border-b border-gray-800 bg-gray-900/50">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-blue-700 rounded-xl flex items-center justify-center shadow-lg shadow-blue-500/20">
                  <Sparkles className="w-5 h-5 text-white" />
                </div>
                <div>
                  <h2 className="text-white font-semibold text-sm">AI Builder</h2>
                  <p className="text-green-400 text-xs flex items-center gap-1">
                    <span className="w-1.5 h-1.5 bg-green-400 rounded-full" />
                    Ready to build
                  </p>
                </div>
              </div>
              <Button
                variant="ghost"
                size="sm"
                className="text-gray-400 hover:text-white hover:bg-gray-800 h-8 w-8 p-0"
              >
                <MoreHorizontal className="w-4 h-4" />
              </Button>
            </div>
          </div>

          {/* Project Structure - Collapsible */}
          <div className="border-b border-gray-800 bg-gray-900/30">
            <ScrollArea className="max-h-48">
              <div className="p-3 space-y-1">
                {/* Screens */}
                {structure.screens.length > 0 && (
                  <div>
                    <button
                      onClick={() => toggleSection('screens')}
                      className="w-full flex items-center gap-2 px-2 py-1 text-gray-400 hover:text-white text-xs"
                    >
                      {expandedSections.includes('screens') ? (
                        <ChevronDown className="w-3 h-3" />
                      ) : (
                        <ChevronRight className="w-3 h-3" />
                      )}
                      <Layout className="w-3 h-3 text-blue-400" />
                      <span>Screens ({structure.screens.length})</span>
                    </button>
                    {expandedSections.includes('screens') && (
                      <div className="ml-5 mt-1 space-y-0.5">
                        {structure.screens.map((screen) => {
                          const Icon = screen.icon;
                          return (
                            <button
                              key={screen.id}
                              onClick={() => setSelectedScreen(screen)}
                              className={`w-full flex items-center gap-2 px-2 py-1 rounded text-xs ${
                                selectedScreen?.id === screen.id
                                  ? 'bg-blue-600/20 text-blue-400'
                                  : 'text-gray-500 hover:text-gray-300'
                              }`}
                            >
                              <Icon className="w-3 h-3" />
                              {screen.name}
                            </button>
                          );
                        })}
                      </div>
                    )}
                  </div>
                )}

                {/* Pages */}
                {structure.pages.length > 0 && (
                  <div>
                    <button
                      onClick={() => toggleSection('pages')}
                      className="w-full flex items-center gap-2 px-2 py-1 text-gray-400 hover:text-white text-xs"
                    >
                      {expandedSections.includes('pages') ? (
                        <ChevronDown className="w-3 h-3" />
                      ) : (
                        <ChevronRight className="w-3 h-3" />
                      )}
                      <Globe className="w-3 h-3 text-green-400" />
                      <span>Pages ({structure.pages.length})</span>
                    </button>
                    {expandedSections.includes('pages') && (
                      <div className="ml-5 mt-1 space-y-0.5">
                        {structure.pages.map((page) => {
                          const Icon = page.icon;
                          return (
                            <button
                              key={page.id}
                              onClick={() => setSelectedScreen(page)}
                              className={`w-full flex items-center gap-2 px-2 py-1 rounded text-xs ${
                                selectedScreen?.id === page.id
                                  ? 'bg-green-600/20 text-green-400'
                                  : 'text-gray-500 hover:text-gray-300'
                              }`}
                            >
                              <Icon className="w-3 h-3" />
                              {page.name}
                            </button>
                          );
                        })}
                      </div>
                    )}
                  </div>
                )}

                {/* Data Models */}
                <div>
                  <button
                    onClick={() => toggleSection('data')}
                    className="w-full flex items-center gap-2 px-2 py-1 text-gray-400 hover:text-white text-xs"
                  >
                    {expandedSections.includes('data') ? (
                      <ChevronDown className="w-3 h-3" />
                    ) : (
                      <ChevronRight className="w-3 h-3" />
                    )}
                    <Database className="w-3 h-3 text-purple-400" />
                    <span>Data Models ({structure.dataModels.length})</span>
                  </button>
                  {expandedSections.includes('data') && (
                    <div className="ml-5 mt-1 space-y-0.5">
                      {structure.dataModels.map((model) => (
                        <div
                          key={model.id}
                          className="flex items-center justify-between px-2 py-1 text-xs text-gray-500"
                        >
                          <span>{model.name}</span>
                          <span className="text-gray-600">{model.fields.length} fields</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                {/* Flows */}
                <div>
                  <button
                    onClick={() => toggleSection('flows')}
                    className="w-full flex items-center gap-2 px-2 py-1 text-gray-400 hover:text-white text-xs"
                  >
                    {expandedSections.includes('flows') ? (
                      <ChevronDown className="w-3 h-3" />
                    ) : (
                      <ChevronRight className="w-3 h-3" />
                    )}
                    <GitBranch className="w-3 h-3 text-orange-400" />
                    <span>Flows ({structure.flows.length})</span>
                  </button>
                  {expandedSections.includes('flows') && (
                    <div className="ml-5 mt-1 space-y-0.5">
                      {structure.flows.map((flow) => (
                        <div
                          key={flow.id}
                          className="flex items-center justify-between px-2 py-1 text-xs text-gray-500"
                        >
                          <span>{flow.name}</span>
                          <span className="text-gray-600">{flow.steps.length} steps</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </ScrollArea>
          </div>

          {/* Messages */}
          <ScrollArea className="flex-1">
            <div className="p-4 space-y-4">
              {messages.map((message) => (
                <div
                  key={message.id}
                  className={`flex gap-3 ${message.role === 'user' ? 'flex-row-reverse' : ''}`}
                >
                  <div
                    className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 ${
                      message.role === 'user'
                        ? 'bg-gray-700'
                        : 'bg-gradient-to-br from-blue-500 to-blue-700 shadow-md'
                    }`}
                  >
                    {message.role === 'user' ? (
                      <User className="w-4 h-4 text-gray-300" />
                    ) : (
                      <Bot className="w-4 h-4 text-white" />
                    )}
                  </div>
                  <div className={`flex-1 ${message.role === 'user' ? 'text-right' : ''}`}>
                    <div
                      className={`inline-block p-3 rounded-2xl max-w-[95%] text-left ${
                        message.role === 'user'
                          ? 'bg-blue-600 text-white rounded-br-md'
                          : 'bg-gray-800/80 text-gray-100 rounded-bl-md border border-gray-700/50'
                      }`}
                    >
                      <p className="text-sm whitespace-pre-wrap leading-relaxed">{message.content}</p>
                    </div>
                    <p className="text-gray-500 text-xs mt-1.5 px-1">
                      {formatTime(message.timestamp)}
                    </p>
                  </div>
                </div>
              ))}

              {/* Generation Progress */}
              {isGenerating && generationSteps.length > 0 && (
                <div className="flex gap-3">
                  <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-blue-700 flex items-center justify-center shadow-md">
                    <Bot className="w-4 h-4 text-white" />
                  </div>
                  <div className="bg-gray-800/80 border border-gray-700/50 rounded-2xl rounded-bl-md p-4">
                    <div className="space-y-2">
                      {generationSteps.map((step, i) => (
                        <div key={i} className="flex items-center gap-2">
                          {i < currentStep ? (
                            <Check className="w-4 h-4 text-green-400" />
                          ) : i === currentStep ? (
                            <Loader2 className="w-4 h-4 text-blue-400 animate-spin" />
                          ) : (
                            <Circle className="w-4 h-4 text-gray-600" />
                          )}
                          <span
                            className={`text-sm ${
                              i <= currentStep ? 'text-gray-200' : 'text-gray-500'
                            }`}
                          >
                            {step}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>
          </ScrollArea>

          {/* Suggestions */}
          {messages.length <= 2 && !isGenerating && (
            <div className="p-3 border-t border-gray-800 bg-gray-900/30">
              <p className="text-gray-500 text-xs mb-2 flex items-center gap-1">
                <Lightbulb className="w-3 h-3" />
                Try saying...
              </p>
              <div className="flex flex-wrap gap-1.5">
                {suggestedPrompts.slice(0, 3).map((prompt, i) => (
                  <button
                    key={i}
                    onClick={() => handleSuggestionClick(prompt)}
                    className="px-2.5 py-1.5 bg-gray-800/50 hover:bg-gray-800 border border-gray-700/50 rounded-lg text-xs text-gray-400 hover:text-white transition-colors"
                  >
                    {prompt}
                  </button>
                ))}
              </div>
            </div>
          )}

          {/* Input */}
          <div className="p-4 border-t border-gray-800 bg-gray-900/50">
            <div className="relative">
              <Textarea
                ref={inputRef}
                value={inputValue}
                onChange={(e) => setInputValue(e.target.value)}
                onKeyDown={handleKeyPress}
                placeholder="Describe what you want to build or change..."
                disabled={isGenerating}
                className="min-h-[80px] max-h-[160px] pr-12 bg-gray-800/50 border-gray-700 text-white placeholder:text-gray-500 focus:border-blue-500 focus:ring-1 focus:ring-blue-500/50 resize-none rounded-xl"
              />
              <Button
                size="sm"
                onClick={handleSendMessage}
                disabled={!inputValue.trim() || isGenerating}
                className="absolute right-3 bottom-3 bg-blue-600 hover:bg-blue-700 text-white h-8 w-8 p-0 rounded-lg shadow-lg shadow-blue-500/20 disabled:opacity-50"
              >
                {isGenerating ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Send className="w-4 h-4" />
                )}
              </Button>
            </div>
            <div className="flex items-center justify-between mt-2">
              <p className="text-gray-500 text-xs">
                Press <kbd className="px-1.5 py-0.5 bg-gray-800 rounded text-gray-400">Enter</kbd> to send
              </p>
              <div className="flex items-center gap-1 text-gray-500 text-xs">
                <Zap className="w-3 h-3 text-yellow-500" />
                <span>{user?.credits || 1850} credits</span>
              </div>
            </div>
          </div>
        </div>

        {/* Right Panel - Preview */}
        <div className="flex-1 flex flex-col bg-gray-900/20">
          {/* Preview Header */}
          <div className="h-12 border-b border-gray-800 flex items-center justify-between px-4 bg-gray-900/30">
            <div className="flex items-center gap-2">
              <button
                onClick={() => setShowSidebar(!showSidebar)}
                className="p-1.5 text-gray-400 hover:text-white transition-colors rounded hover:bg-gray-800"
              >
                {showSidebar ? <PanelLeftClose className="w-5 h-5" /> : <PanelLeft className="w-5 h-5" />}
              </button>
              <div className="h-4 w-px bg-gray-800" />
              <Eye className="w-4 h-4 text-gray-400" />
              <span className="text-gray-300 text-sm font-medium">Preview</span>
              {selectedScreen && (
                <>
                  <span className="text-gray-600">—</span>
                  <span className="text-gray-400 text-sm">{selectedScreen.name}</span>
                </>
              )}
            </div>
            <div className="flex items-center gap-1 bg-gray-800 rounded-lg p-1">
              {[
                { id: 'mobile', icon: Smartphone },
                { id: 'tablet', icon: Tablet },
                { id: 'desktop', icon: Monitor },
              ].map(({ id: viewId, icon: Icon }) => (
                <button
                  key={viewId}
                  onClick={() => setDeviceView(viewId)}
                  className={`p-1.5 rounded-md transition-colors ${
                    deviceView === viewId
                      ? 'bg-gray-700 text-white'
                      : 'text-gray-400 hover:text-white'
                  }`}
                >
                  <Icon className="w-4 h-4" />
                </button>
              ))}
            </div>
          </div>

          {/* Preview Content */}
          <div className="flex-1 flex items-center justify-center p-8 overflow-auto bg-gray-950/50">
            <div
              className={`bg-white rounded-2xl shadow-2xl overflow-hidden transition-all duration-300 ${
                deviceView === 'mobile'
                  ? 'w-[375px] h-[667px]'
                  : deviceView === 'tablet'
                  ? 'w-[768px] h-[600px]'
                  : 'w-full max-w-5xl h-full max-h-[700px]'
              }`}
            >
              {/* Mock App Preview */}
              <div className="h-full flex flex-col">
                {/* App Header */}
                <div className="h-14 bg-gradient-to-r from-blue-600 to-blue-700 flex items-center justify-between px-4">
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 bg-white/20 rounded-lg" />
                    <div className="h-4 w-20 bg-white/30 rounded" />
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-8 h-8 bg-white/20 rounded-full" />
                  </div>
                </div>

                {/* App Content */}
                <div className="flex-1 bg-gray-50 p-4 overflow-auto">
                  {/* Welcome Section */}
                  <div className="mb-6">
                    <div className="h-6 w-32 bg-gray-300 rounded mb-2" />
                    <div className="h-4 w-48 bg-gray-200 rounded" />
                  </div>

                  {/* Stats Cards */}
                  <div className={`grid ${deviceView === 'mobile' ? 'grid-cols-2' : 'grid-cols-4'} gap-3 mb-6`}>
                    {[1, 2, 3, 4].map((i) => (
                      <div key={i} className="bg-white rounded-xl p-4 shadow-sm">
                        <div className="w-8 h-8 bg-blue-100 rounded-lg mb-2" />
                        <div className="h-5 w-12 bg-gray-300 rounded mb-1" />
                        <div className="h-3 w-16 bg-gray-200 rounded" />
                      </div>
                    ))}
                  </div>

                  {/* Content Section */}
                  <div className="bg-white rounded-xl p-4 shadow-sm mb-4">
                    <div className="h-5 w-24 bg-gray-300 rounded mb-3" />
                    <div className="space-y-3">
                      {[1, 2, 3].map((i) => (
                        <div key={i} className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg">
                          <div className="w-10 h-10 bg-gray-200 rounded-full" />
                          <div className="flex-1">
                            <div className="h-4 w-24 bg-gray-300 rounded mb-1" />
                            <div className="h-3 w-32 bg-gray-200 rounded" />
                          </div>
                          <div className="w-6 h-6 bg-gray-200 rounded" />
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Action Button */}
                  <div className="bg-blue-600 text-white rounded-xl p-4 text-center">
                    <div className="h-4 w-24 bg-white/30 rounded mx-auto" />
                  </div>
                </div>

                {/* Bottom Navigation */}
                <div className="h-16 bg-white border-t border-gray-200 flex items-center justify-around px-4">
                  {[Home, BarChart3, Plus, Bell, User].map((Icon, i) => (
                    <div
                      key={i}
                      className={`w-10 h-10 rounded-full flex items-center justify-center ${
                        i === 0 ? 'bg-blue-100' : ''
                      }`}
                    >
                      <Icon className={`w-5 h-5 ${i === 0 ? 'text-blue-600' : 'text-gray-400'}`} />
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Builder;
